subscription SubscribeSteps($gameStateInput: GameStateInputType!) {
  generateSteps(gameStateInput: $gameStateInput) {
    coordinate {
      x
      y
    }
    throttle
  }
}

#{
#  "gameStateInput": {
#    "playerUnits": [
#      {
#        "coordinate": {
#          "x": 0,
#          "y": 0
#        },
#        "speed": 0,
#        "mass": 10,
#        "friction": 0.01
#      }
#    ],
#    "enemyUnits": [
#      {
#        "coordinate": {
#          "x": 0,
#          "y": 5000
#        },
#        "speed": 0,
#        "mass": 50,
#        "friction": 0.8
#      }
#    ]
#  }
#}